In [1]:
import os

In [2]:
os.path.sys.path.append('../utils')

In [3]:
import nnViz

In [4]:
import keras

Using TensorFlow backend.


In [36]:
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.layers import Input
import numpy as np 


inputs = Input( shape = (3,) )
h1 = Dense( 2 )( inputs )
predictions = Dense ( 1 )( h1 )

model = Model( inputs=inputs, outputs=predictions )
model_h = Model( inputs=inputs, outputs=h1 )

x = np.array([1,2,3])
x = np.expand_dims(x, axis=0)

a = model.predict(x=x)
b = model_h.predict(x=x)
print(x)
print(a)
print(b)

[[1 2 3]]
[[ 0.22903305]]
[[-2.03156757 -0.12043184]]


In [47]:
for layer in model.layers:
    
    weights = layer.get_weights()
    if weights != []:
        print(layer.units)
        print(weights[0])
        print(weights[1])

2
[[ 1.06006122 -1.03452468]
 [-0.09038389  1.08882761]
 [-0.97028697 -0.42118746]]
[ 0.  0.]
1
[[-0.14829993]
 [ 0.59991014]]
[ 0.]


In [34]:
import importlib
importlib.reload(nnViz)

<module 'nnViz' from '../utils\\nnViz.py'>

In [35]:
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10,10))

nnViz.visualize_model(model)

IndexError: list index out of range

In [25]:
a

array([[ 0.23503187]], dtype=float32)